# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/gigaset/GX4/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)



ifneq ($(filter GX4 vidofnir,$(TARGET_DEVICE)),)


endif
