# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/gigaset/GX4/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)



ifneq ($(filter GX4 vidofnir,$(TARGET_DEVICE)),)

RADIO_FILES := $(wildcard $(LOCAL_PATH)/radio/$(TARGET_DEVICE)/*)
$(foreach f, $(notdir $(RADIO_FILES)), \
    $(call add-radio-file,radio/$(TARGET_DEVICE)/$(f)))

endif
